modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/Christofmeg/BrutalHarvest/issues"
license="The MIT License (MIT)"
[[mods]]
    modId="brutalharvest"
    version="${version}"
    displayName="Brutal Harvest"
    displayURL="https://github.com/Christofmeg/BrutalHarvest"
    logoFile="icon.png"
    authors="Christofmeg, tristanh"
    description=""
[[dependencies.brutalharvest]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.brutalharvest]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,)"
    ordering="NONE"
    side="BOTH"
